<h1>Section 1: Graph-Tool<h1>
        This section includes testing of the basic Graph-Tool functionalities

In [ ]:
from graph_tool.all import *


(ipykernel_launcher.py:53375): Gtk-WARNING **: 10:29:16.602: Locale not supported by C library.
	Using the fallback 'C' locale.
objc[53375]: Class GNotificationCenterDelegate is implemented in both /Users/xihan/miniconda3/envs/gt/lib/libgio-2.0.0.dylib (0x1a5970b50) and /usr/local/opt/glib/lib/libgio-2.0.0.dylib (0x1a9e09330). One of the two will be used. Which one is undefined.


In [ ]:
g = Graph(directed=False)
v1 = g.add_vertex()
v2 = g.add_vertex()
v3 = g.add_vertex()
e1 = g.add_edge(v1, v2)
e2 = g.add_edge(v1, v3)

In [ ]:
graph_draw(g, vertex_text=g.vertex_index, output="two-nodes.pdf")

In [ ]:
print(v1.out_degree())
print(e1.source(), e1.target())

2
0 1


In [ ]:
vlist = g.add_vertex(10)
print(len(list(vlist)))

10


In [ ]:
e3 = g.add_edge(4, 5)

In [ ]:
for v in g.iter_vertices():
    print(v)
for e in g.iter_edges():
    print(e)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
[0, 1]
[0, 2]
[4, 5]


In [ ]:
g.get_out_degrees(g.get_vertices())

array([2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0], dtype=uint64)

In [ ]:
from numpy.random import randint

g = Graph()
g.add_vertex(100)

# insert some random links
num_edges = 10
for s,t in zip(randint(0, 100, num_edges), randint(0, 100, num_edges)):
    g.add_edge(g.vertex(s), g.vertex(t))
    
#print edges
print("edges added:")
for i in g.iter_edges():
    print(i)

vprop_double = g.new_vertex_property("double")            # Double-precision floating point
v = g.vertex(10)
vprop_double[v] = 3.1416
print("property of vertex {}: {}".format(v, vprop_double[v]))

vprop_vint = g.new_vertex_property("vector<int>")         # Vector of ints
v = g.vertex(40)
vprop_vint[v] = [1, 3, 42, 54]
print("property of vertex {}: {}".format(v, vprop_vint[v]))

eprop_dict = g.new_edge_property("object")                # Arbitrary Python object.
e = g.edges().next()
eprop_dict[e] = {"name": "foo", "weight": 42} 
print("property of edge {}: {}".format(e, eprop_dict[e]))

gprop_bool = g.new_graph_property("bool")                 # Boolean
gprop_bool[g] = True


edges added:
[6, 7]
[15, 98]
[18, 27]
[39, 22]
[50, 26]
[54, 10]
[71, 78]
[73, 7]
[75, 84]
[79, 25]
property of vertex 10: 3.1416
property of vertex 40: array([ 1,  3, 42, 54], dtype=int32)
property of edge (6, 7): {'name': 'foo', 'weight': 42}


In [ ]:
# See what the initializations are for each of the graph properties
for prop in ["int", "vector<int>", "double", "vector<double>", "object", "bool"]:
    gprop = g.new_graph_property(prop)
    g.graph_properties["custom property"] = gprop
    print(prop, g.graph_properties["custom property"])

int 0
vector<int> array([], dtype=int32)
double 0.0
vector<double> array([], dtype=float64)
object None
bool 0


In [ ]:
g.vp.custom_property = vprop = g.new_vertex_property("bool")
g.vp.custom_property[g.vertex(0)] = True
print(g.vp.custom_property[g.vertex(0)])

1


In [ ]:
import os
working_dir = '.' #placeholder

'''
Saves the graph g to {target path} with name {name}
'''
def save_graph(g, name, target_path):
    abs_path = os.path.join(working_dir, target_path)
    g.save("{}.xml.gz".format(name))
    

'''
Loads the graph g from {source path} 

Returns: the loaded graph 
'''
def load_graph(source_path):
    return load_graph(source_path)


In [ ]:
'''
converts the following to a unified graph:
    
    - agent ids
    - agent intrinsics
    - driving forces
    - opinion
    
Input:

    agents:          numpy array of agent intrinsics
    clusters:        {"cluster_i": a list of agent ids}
    driving_forces:  numpy array of the driving forces
    opinions:        binary numpy array of the opinions
    
'''
def to_graph(agents, clusters, driving_forces, opinions):
    pass
    

<h2>Section 2: the model will be implemented here<h2>

In [3]:
import numpy as np
import scipy
from scipy.stats import norm
import math

In [4]:
'''
Global configurations
'''
k_alpha = 1
k_beta = .5
E_profit = 10
K_self_coupling = -2

num_clusters = 5
num_agents = 20

In [1]:
from random import randint

# partition functions

import random 
def partition_uniform_random (num_agents, n):
    l = list(range(num_agents))
    random.shuffle(l)
    return [l[i::n] for i in range(n)]


'''
Create {num_clusters} random clusters
if cluster_specific = True, use initialise_driving_force() to initialise cluster-specific driving force

Returns: 
           cluster_elements:  {"cluster_i": numpy array of agent ids in cluster i}
           driving_forces:    numpy array of driving forces (properly-/0-initialised)
           agents:            numpy array of agent intrinsics
           opinions:          a numpy binary array of the opinions

'''

def create_clusters(num_clusters, num_agents, cluster_specific=False):
    assert num_agents >= num_clusters >= 1
  
        
    #initialise driving forces
    if cluster_specific:
        driving_forces = initialise_driving_forces(num_agents)
    else:
        driving_forces = np.zeros(num_agents)
        
    #initialise agents intrinsics
    agents = initialise_agents(num_agents)
    
    cluster_elements = partition_uniform_random(num_agents, num_clusters)

    #initialise opinions
    opinions = initialise_opinions(num_agents)
        
    return cluster_elements, driving_forces, agents, opinions
        
    
'''
Initialises the driving forces for each agent in {agents}
You can define initialization schemes here

Retuns: a numpy array containing the driving force of each agent

'''   
def initialise_driving_forces(num_agents):
    driving_forces = np.random.rand(num_agents) #hard-coded for now
    return driving_forces
    
'''
Initialises the intrinsics for each agent in {agents}
You can define initialization schemes here

Retuns: a numpy array containing the intrinsics of each agent
'''
def initialise_agents(num_agents):
    return np.zeros(num_agents) #hard-coded for now


'''
Initialises the opinions for each agent in {agents}
You can define initialization schemes here

Retuns: a numpy array containing the opinions of each agent
'''
def initialise_opinions(num_agents):
    return np.random.randint(2, size=num_agents) #hard-coded for now



In [5]:
clusters, driving_forces, agents, opinions = create_clusters(num_clusters, num_agents)
print("clusters: {}\n\n driving forces: {}\n\n agents:{}\n\n opinions:{}".format(clusters, driving_forces, agents, opinions))

clusters: [[10, 15, 19, 1], [11, 18, 7, 17], [13, 8, 16, 9], [3, 6, 4, 5], [2, 14, 0, 12]]

 driving forces: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 agents:[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 opinions:[0 1 1 1 1 0 0 1 0 0 1 1 1 0 0 0 1 0 0 0]


In [ ]:
'''
    updates the agent intrinsics (optional), opinions and driving forces 
'''

# TODO: need to fix this
def update_driving_forces(driving_forces, agents, clusters, opinions, update_agents=False):
    # update each cluster locally resp. each agent
    print("updating clusters ...")
    updated_agents = np.zeros(len(driving_forces))
    for n in range(len(clusters)):
        print("cluster ", n)
        agents_ids = clusters["cluster_{}".format(n)]
        cluster_size = len(agents_ids)
        
        # update the driving force of each agent in the current cluster
        # based on the other agents in the cluster
        
        for a in agents_ids:
            updated_agents[a] = np.sum([x for x in driving_forces[agents_ids] if x != a])
            
        for a in agents_ids:
            driving_forces[a] = E_profit + np.sum(updated_agents[agents_ids]) * k_alpha
            print("agent {} obtained a driving force of {}".format(a, driving_forces[a]))
        print("resulting global df: {}\n".format(driving_forces))
        
            
    return updated_agents, driving_forces #currently it returns the unchanged agent intrinsics

In [ ]:
upd_agts, upd_df = update_driving_forces(driving_forces, opinions, clusters, opinions)
upd_agts, upd_df

updating clusters ...
cluster  0
agent 11 obtained a df of 10.0
agent 2 obtained a df of 10.0
agent 9 obtained a df of 10.0
agent 12 obtained a df of 10.0
resulting global df: [ 0.  0. 10.  0.  0.  0.  0.  0.  0. 10.  0. 10. 10.  0.  0.  0.  0.  0.
  0.  0.]

cluster  1
resulting global df: [ 0.  0. 10.  0.  0.  0.  0.  0.  0. 10.  0. 10. 10.  0.  0.  0.  0.  0.
  0.  0.]

cluster  2
agent 7 obtained a df of 10.0
agent 5 obtained a df of 10.0
agent 0 obtained a df of 10.0
agent 6 obtained a df of 10.0
agent 13 obtained a df of 10.0
agent 15 obtained a df of 10.0
agent 18 obtained a df of 10.0
resulting global df: [10.  0. 10.  0.  0. 10. 10. 10.  0. 10.  0. 10. 10. 10.  0. 10.  0.  0.
 10.  0.]

cluster  3
agent 4 obtained a df of 10.0
agent 3 obtained a df of 10.0
agent 10 obtained a df of 10.0
resulting global df: [10.  0. 10. 10. 10. 10. 10. 10.  0. 10. 10. 10. 10. 10.  0. 10.  0.  0.
 10.  0.]

cluster  4
agent 17 obtained a df of 10.0
agent 14 obtained a df of 10.0
resulting globa

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([10.,  0., 10., 10., 10., 10., 10., 10.,  0., 10., 10., 10., 10.,
        10., 10., 10.,  0., 10., 10.,  0.]))

In [ ]:
'''
Given the current state, returns a new state

Input: 
       -current_state: (agents' instrinsics, opinions, probabilities of change, driving forces)
       -f:             the state transition function
       
Returns:
       The new state f(current_state)
'''
# TODO: adapt this 
# You can choose whether to unpack current_state or not
def update_state(current_state):
    return transition_funtion(current_state)


'''
You can define state transition functions here
'''
def transition_function(state):
       agents = state[0]
       hi = hi_calculation(state[3])
       state[2] = change_probs(state[3])

       for i in range(len(agents)): 
              new_opinion = opinion(state[1][i], updated_prob)
              state[1][i] = new_opinion
       return state


In [ ]:
'''
Part of modelling the transition function

'''
def normalise_driving_force(driving_forces):
    hi = k_alpha*len(driving_forces) 
    lo = None

    driving_force_normed = driving_forces/hi
    probability = math.erf(driving_force_normed[0])
    print(driving_force_norm[0], probability)


'''
compute the probability of change given a driving force    
'''
def change_probs(driving_force, hi, lo=None):
    probs = np.zeros(len(driving_force))
    for i in range(len(driving_force)):
        if agents[i] < hi:
            probs[i] = math.erf(driving_force[i])#norm.ppf(agents[i])
        else:
            probs[i] = math.erf(hi)
    return probs

'''
The new opinion {x} of an agent given the prob. of change {p}

Can serve as a state transition function
'''
def opinion(x, p):
    res = (np.random.rand(1))[0]
    return 1-x if res < p else x

In [ ]:
#update_state((updated_agents, probs), opinion)

<h1>Section 3: Simulation<h1>
    1.Preprocessing (e.g. what graph models to use)<br>
    2.Simulate the model and visualise the result (e.g. for each timestep)

In [ ]:
# Simulation configs
num_steps = 42
visualise_per = 5

# Simulation loop, e.g.
#
# model = preprocess(data)
#
# clusters, driving_forces, agents, opinions = create_clusters(num_clusters, num_agents)
# current_state = (clusters, driving_forces, agents, opinions)
#
# for i in range(num_steps):
#    if i % visualise_per = 0:
#       visualise(current_state)
#    current_state = update_state(current_state, transition_function)
#
# graph = to_graph(current_state)
# save_graph(graph, graph_name, save_path)
#
#
#
# Note that in the current version we need to convert the current state to a graph
# first in order to visualise it -> maybe improve this



In [ ]:
# --test--  idea : visualize clusters individually
    
import matplotlib.pyplot as plt

def visualise(current_state):
  plt.figure(figsize=(20,10),dpi=80)
  axes=plt.subplot(111)

  for i in range(len(cluster)):
    np.random.seed(2000)
    y = np.random.standard_normal((1000, 2))
    plt.figure(figsize=(7,5))
    
    # assign different colors to different opinion
    plt.scatter(cluster[:, 0], cluster[:, 1], c=y, s=40, cmap=plt.cm.Spectral)
    plt.grid(True)
    plt.xlabel('1st')
    plt.ylabel('2nd')
    plt.title('cluster',i)
    plt.show()

# visualise(current_state)
